image: ghcr.io/cirruslabs/flutter:stable

stages:
  - analyze
  - test
  - build

analyze:
  stage: analyze
  script:
    - flutter pub get
    - flutter analyze

test:
  stage: test
  script:
    - flutter test

build:
  stage: build
  script:
    - echo $KEYSTORE_BASE64 | base64 -d > android/keystore.jks
    - printf "keyAlias=$KEY_ALIAS\nkeyPassword=$KEY_PASSWORD\nstorePassword=$STORE_PASSWORD\nstoreFile=keystore.jks\n" > android/key.properties
    - echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -d > android/app/google-services.json
    - echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -d | head -c 100
    - flutter build apk --release --split-per-abi --dart-define=APPODEAL_KEY=$APPODEAL_KEY
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/